version: 0.2

phases:
  install:
    commands:
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.36.1/trivy_0.36.1_Linux-64bit.deb
      - sudo dpkg -i trivy_0.36.1_Linux-64bit.deb
  pre_build:
    commands:
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_CLUSTER_NAME
      - echo check config
      - kubectl config view --minify
      - echo check kubectl access
      - kubectl get svc
      - echo Logging in to Amazon ECR...
      - docker login --username AWS -p $(aws ecr get-login-password --region ap-south-1) 947681381905.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - echo Building the Docker image...
      - docker build -f DockerFile -t $REPOSITORY_URI -t $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Generating Trivy Report
      - trivy image --timeout 30m --offline-scan $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - echo Ending Trivy Report
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI
      - docker push $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - echo Push the latest image to cluster
      - kubectl apply -f Deployment.yaml
      - kubectl rollout restart Deployment atsinterview -n dev



