apiVersion: apps/v1
kind: Deployment
metadata:
  name: jewel-reportmanager
  namespace: dev
  labels:
    app: jewel-reportmanager
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: jewel-reportmanager
  template:
    metadata:
      labels:
        app: jewel-reportmanager
    spec:
      containers:
        - name: jewel-reportmanager
          image: registry-np.geminisolutions.com/gemeco/jewel_report_manager_beta
          ports:
            - name: jewel-reportmanager
              containerPort: 8004
          imagePullPolicy: Always
          env:
            - name: ENV
              value: beta
      imagePullSecrets:
        - name: regcred