apiVersion: apps/v1
kind: Deployment
metadata:
  name: jewel-dashboardmanager
  namespace: dev
  labels:
    app: jewel-dashboardmanager
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: jewel-dashboardmanager
  template:
    metadata:
      labels:
        app: jewel-dashboardmanager
    spec:
      containers:
        - name: jewel-dashboardmanager
          image: registry-np.geminisolutions.com/gemeco/jewel_dashboard_manager_beta
          ports:
            - name: jewel-dashboardmanager
              containerPort: 8002
          imagePullPolicy: Always
          env:
            - name: ENV
              value: beta
      imagePullSecrets:
        - name: regcred